-- ==============================================================================
-- RUN THIS ENTIRE FILE IN THE SUPABASE SQL EDITOR
-- ==============================================================================

-- 1. Create the Teams table
CREATE TABLE teams (
    team_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    team_name TEXT NOT NULL
);

-- 2. Create the Members table
-- Links to the 'teams' table via foreign key
CREATE TABLE members (
    member_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    team_id BIGINT NOT NULL REFERENCES teams(team_id) ON DELETE CASCADE,
    
    role TEXT NOT NULL CHECK (role IN ('Leader', 'Member')),
    name TEXT NOT NULL,
    roll_number TEXT NOT NULL UNIQUE, -- Crucial: Prevents a student joining multiple teams
    year TEXT NOT NULL,
    section TEXT NOT NULL,
    email TEXT NOT NULL
);

-- ==============================================================================
-- SECURITY FOR WEBSITE SUBMISSIONS (Row Level Security)
-- ==============================================================================

-- Enable RLS on both tables
ALTER TABLE teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE members ENABLE ROW LEVEL SECURITY;

-- Allow public to INSERT new teams (from the website form)
CREATE POLICY "Allow public inserts on teams" ON teams 
FOR INSERT WITH CHECK (true);

-- Allow public to INSERT new members (from the website form)
CREATE POLICY "Allow public inserts on members" ON members 
FOR INSERT WITH CHECK (true);

-- Allow public to DELETE their team ONLY IF the member insertion failed
-- We secure this by only allowing deletes within exactly 2 minutes of the team creation.
CREATE POLICY "Allow public temporary revert on teams" ON teams
FOR DELETE USING (
  created_at > (now() - interval '2 minutes')
);

-- Allow public to select from 'teams' ONLY to retrieve their newly generated team_id
CREATE POLICY "Allow public select on teams" ON teams FOR SELECT USING (true);

-- Deny all public reads on 'members' (Hackers cannot download the student databases)
CREATE POLICY "Deny public select members" ON members FOR SELECT USING (false);

-- ==============================================================================
-- 3. CERTIFICATE EXPORTS TABLE (Flattened version of the team strictly for CSV Exporting)
-- ==============================================================================

CREATE TABLE certificate_exports (
    export_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    team_id BIGINT NOT NULL REFERENCES teams(team_id) ON DELETE CASCADE,
    
    team_name TEXT NOT NULL,
    leader_name TEXT NOT NULL,
    leader_email TEXT NOT NULL,
    member1_name TEXT NOT NULL,
    member1_email TEXT NOT NULL,
    member2_name TEXT NOT NULL,
    member2_email TEXT NOT NULL,
    member3_name TEXT,
    member3_email TEXT,
    member4_name TEXT,
    member4_email TEXT
);

-- Security for Export Table
ALTER TABLE certificate_exports ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public inserts on certificate_exports" ON certificate_exports FOR INSERT WITH CHECK (true);
CREATE POLICY "Deny public select certificate_exports" ON certificate_exports FOR SELECT USING (false);

-- ==============================================================================
-- 4. REGISTRATION SPREADSHEET TABLE (Hard data for direct dashboard view/export)
-- ==============================================================================
CREATE TABLE registration_spreadsheet (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    team_id BIGINT REFERENCES teams(team_id) ON DELETE CASCADE,
    
    "Team / Number" TEXT,
    "Role" TEXT,
    "Name" TEXT,
    "Roll No" TEXT,
    "Year" TEXT,
    "Section" TEXT,
    "Email" TEXT
);

-- ==============================================================================
-- 5. ORDERED REGISTRATIONS TABLE (Forced Column Order for Perfect Excel/Dashboard)
-- Uses numbered keys to prevent Supabase/Excel from alphabetizing columns.
-- ==============================================================================
CREATE TABLE ordered_registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    team_id BIGINT REFERENCES teams(team_id) ON DELETE CASCADE,
    
    "00_Team_Name" TEXT,
    "01_Leader_Name" TEXT,
    "02_Leader_Roll_No" TEXT,
    "03_Leader_Email" TEXT,
    "04_Leader_Year" TEXT,
    "05_Leader_Section" TEXT,
    
    "06_Member_1_Name" TEXT,
    "07_Member_1_Roll_No" TEXT,
    "08_Member_1_Email" TEXT,
    "09_Member_1_Year" TEXT,
    "10_Member_1_Section" TEXT,
    
    "11_Member_2_Name" TEXT,
    "12_Member_2_Roll_No" TEXT,
    "13_Member_2_Email" TEXT,
    "14_Member_2_Year" TEXT,
    "15_Member_2_Section" TEXT,
    
    "16_Member_3_Name" TEXT,
    "17_Member_3_Roll_No" TEXT,
    "18_Member_3_Email" TEXT,
    "19_Member_3_Year" TEXT,
    "20_Member_3_Section" TEXT,
    
    "21_Member_4_Name" TEXT,
    "22_Member_4_Roll_No" TEXT,
    "23_Member_4_Email" TEXT,
    "24_Member_4_Year" TEXT,
    "25_Member_4_Section" TEXT
);

-- Enable RLS
ALTER TABLE ordered_registrations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public inserts on ordered_registrations" ON ordered_registrations FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public select on ordered_registrations" ON ordered_registrations FOR SELECT USING (true);


